### PR TITLE
add random X-Forwarded-For header generation

### PR DESCRIPTION
**Pull request by elindsey**
I added an option to randomly generate X-Forwarded-For IPs (currently only v4) - we needed this to accurately load test some of our infra that relies on that header.

A few questions for you:
1. Do you have any interest in this upstream?
2. If so, what C++ version should I target? The patch is currently 17 to avoid an extra copy, but I'm not sure if that drops compiler versions you'd like to support.

### CODE REVIEW

**Comment by tinselcity** [comment]
It's funny I had a need for a similar thing in another repo, but your code seems more elegant -_and correct_.  With respect to which C++ version to target, at my work we still have to be able to target older compilers.  The contribution looks useful -I wonder if it can be optionally `#ifdef`'d in if C++17 is supported via a CMake configuration.  I'll look around to see what's available.

**Comment by elindsey** [comment]
> I wonder if it can be optionally #ifdef'd in if C++17 is supported via a CMake configuration

Here's a diff adding support for pre-17 and a bit of cmake boilerplate to toggle between the two implementations.

It's a bit messy because the current build flag is c++0x, so I can't count on it having `<random>` (`std=c++0x` was added in gcc 4.3, but `<random>` didn't show up until 4.5).

If you wanted to bump the min to `-std=c++11`, then the code gets much simpler as both codepaths can share address generation and all but one ifdef disappear, but that would limit support to gcc >= 4.7 and clang >= 3.3.

**Comment by tinselcity** [comment]
Thanks -merging...

**Comment by elindsey** [comment]
No problem - I'd kept 0x only because it was the current project default. 🙂 

The new patch builds correctly under 98. Two unrelated braced initializations needed to be fixed.

**Pull request merged**
